apiVersion: v1
kind: ConfigMap
metadata:
  name: unilever-config
  namespace: unilever-poc
data:
  DB_HOST: "unilever-poc-db.cja2wugmwcyb.eu-north-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  AZURE_OPENAI_ENDPOINT: "https://ratho-ml5ajghj-swedencentral.cognitiveservices.azure.com/"
  AZURE_OPENAI_DEPLOYMENT: "gpt-4o-harshal"
  AZURE_OPENAI_MODEL: "gpt-4o"
  AZURE_OPENAI_API_VERSION: "2024-12-01-preview"
  AGENT_LLM_PROVIDER: "azure"
  EVALUATOR_LLM_PROVIDER: "azure"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  AWS_REGION: "eu-north-1"
  AZURE_AD_TENANT_ID: "fb9f2128-0f50-4c51-b96b-428efb273c38"
  AZURE_AD_CLIENT_ID: "012bb707-9528-4678-b90b-34782146ffae"
  AZURE_AD_AUDIENCE: "api://012bb707-9528-4678-b90b-34782146ffae"
  AUTH_ENABLED: "true"
  EVALUATION_THRESHOLD: "0.40"
  DRIFT_HIGH_THRESHOLD: "0.85"
  DRIFT_MEDIUM_THRESHOLD: "0.65"
  LOG_LEVEL: "INFO"
  ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173,http://k8s-unilever-unilever-4a15c3fc98-1957872568.eu-north-1.elb.amazonaws.com,https://d3a8i8fww4yp2x.cloudfront.net"
  ALERT_EMAIL_ENABLED: "true"
  ALERT_SLACK_ENABLED: "false"
  AWS_SES_SENDER_EMAIL: "h22244080@gmail.com"
  AWS_SNS_TOPIC_ARN: "arn:aws:sns:eu-north-1:750573229682:unilever-procurement-alerts"
  ALERT_RECIPIENT_EMAILS: "h22244080@gmail.com"
