apiVersion: v1
kind: Secret
metadata:
  name: unilever-secrets
  namespace: unilever-poc
type: Opaque
data:
  DB_PASSWORD: cG9zdGdyZXM=
  AZURE_OPENAI_API_KEY: QXJUUnZabDRBQ09BY3BkNlpRNTBvSGF6QWRDTWcxdzY3RURCM2hSTkZRQjRnbFNQSXBKZUpRUUo5OUNCQUNmaE1rNVhKM3czQUFBQUFDT0d3RmdE
  AZURE_AD_CLIENT_SECRET: ZE5jOFF+dkRDZX5tYXVEd29JeHllWGVibmFYQm5yZ1AxM191NmE0NA==
  # AWS credentials injected at deploy time by CD pipeline - never commit here
